services:
  backend:
    container_name: backend-ecommerce
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      DB_HOST: "dpg-co16e8ol6cac73cq45g0-a.singapore-postgres.render.com/"
      DB_PORT: 5432
      DB_NAME: "techshopdb_isr7"
      DB_USERNAME: "admin"
      DB_PASSWORD: "aDD11la8bNZ4qS7IUHEUIrGeavBNn416"
    volumes:
      - ./backend/:/app
      - ./backend/.m2:/root/.m2
    networks:
      - default
      - database-nw
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 5005:5005
      - 35729:35729
networks:
  database-nw:
    external: true

